version: '3.8'

services:
  backend:
    container_name: backend
    build: ./chatapp
    restart: unless-stopped
    expose:
      - 8000
    command: gunicorn chatapp.wsgi:application --bind 0.0.0.0:8000 -w 2

  frontend:
    build: ./chatapp-frontend
    volumes:
      - ./chatapp-frontend:/app
    expose:
      - 3000
    command: npm start 

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c "mkdir -p /app/log/nginx && nginx -g 'daemon off;'"
    depends_on:
      - backend
      - frontend
