# Generated by Django 5.0.7 on 2024-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
            preserve_default=False,
        ),
    ]
